export const FETCH_END = 'setArticles'
export const FETCH_START = 'setLoading'
export const PURGE_AUTH = 'logOut'
export const SET_EMPLOYEE = 'setEmployee'
export const SET_AUTH = 'setUser'
export const SET_ERROR = 'setError'
export const UPDATE_EMPLOYEE_IN_LIST = 'updateEmployeeInList'
export const RESET_STATE = 'resetModuleState'
